'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {social} from '../../lib/social-client';
export default function ConnectionsPage() {
 const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[email,setEmail]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function load(signal) {setItems(await social('connections',undefined,signal));}
 useEffect(()=>{const c=new AbortController();load(c.signal).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>setLoading(false));return()=>c.abort();},[]);
 async function act(action,payload) {setBusy(true);setError('');setMessage('');try {await social(action,payload);await load();if(action==='request_connection'){setMessage('If this email belongs to a LinkLemon account, they can find your request in Connections and their inbox.');setEmail('');}}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <main className="mx-auto max-w-md p-4"><h1 className="text-2xl font-semibold">Connections</h1><p className="mt-2 text-sm text-gray-600">Build your circle. Once someone accepts, you can include each other in quick outings.</p>
 <form className="my-5 rounded-2xl border bg-white p-4" onSubmit={e=>{e.preventDefault();act('request_connection',{email:email.trim().toLowerCase()});}}><label htmlFor="connection-email" className="block font-medium">Connect by email</label><input id="connection-email" type="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} className="mt-2 w-full rounded-lg border p-3" placeholder="Their LinkLemon email"/><button disabled={busy} className="mt-3 rounded-xl bg-yellow-300 px-4 py-3 font-semibold disabled:opacity-50">{busy?'Please wait…':'Send connection request'}</button><p className="mt-2 text-xs text-gray-600">They must accept before you can notify them directly. No email is sent.</p></form>
 {message && <p role="status" className="mb-4 rounded-xl bg-green-50 p-3 text-sm">{message}</p>}{error && <p role="alert" className="mb-4 text-red-700">{error}</p>}
 {loading?<p role="status">Loading connections…</p>:<>{[['pending','Requests'],['accepted','Your connections']].map(([status,title])=><section key={status} className="mb-5"><h2 className="font-semibold">{title}</h2>{!items.some(i=>i.status===status)?<p className="mt-2 text-sm text-gray-600">{status==='pending'?'No pending requests.':'Your accepted connections will appear here.'}</p>:<ul className="mt-2 divide-y rounded-xl border bg-white">{items.filter(i=>i.status===status).map(i=><li key={i.id} className="p-4"><p className="font-medium">{i.name}</p>{status==='pending'?(i.incoming?<div className="mt-2 flex gap-4"><button disabled={busy} className="font-medium underline" onClick={()=>act('respond_connection',{id:i.id,status:'accepted'})}>Accept</button><button disabled={busy} className="underline" onClick={()=>act('respond_connection',{id:i.id,status:'declined'})}>Decline</button></div>:<p className="mt-1 text-sm text-gray-600">Request sent · waiting for acceptance</p>):<button disabled={busy} className="mt-2 text-sm underline" onClick={()=>{if(window.confirm('Disconnect from '+i.name+'? You will no longer be able to include each other in new outings.'))act('disconnect',{id:i.id});}}>Disconnect</button>}</li>)}</ul>}</section>)}</>}
 <Link href="/heading-out" className="underline">Make a quick plan</Link></main>;
}
