'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {social,outingTime} from '../../../lib/social-client';
export default function OutingPage({params}) {
 const [outing,setOuting]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[clock,setClock]=useState(Date.now());
 async function load(signal){const response=await fetch('/api/social?action=outing&id='+encodeURIComponent(params.id),{cache:'no-store',signal:signal || AbortSignal.timeout(15000)});const result=await response.json();if(!response.ok)throw new Error(result.error || 'Could not load this outing.');setOuting(result.data[0] || null);}
 useEffect(()=>{const c=new AbortController();async function refresh(){try{await load(c.signal);setClock(Date.now());setError('');}catch(e){if(e.name!=='AbortError')setError(e.message);}finally{setLoading(false);}}refresh();const timer=setInterval(refresh,60000);return()=>{c.abort();clearInterval(timer);};},[params.id]);
 async function act(action,payload){setBusy(true);setError('');try{await social(action,{id:params.id,...payload});await load();setClock(Date.now());}catch(e){setError(e.message);}finally{setBusy(false);}}
 const ended=outing && (outing.cancelled_at || new Date(outing.ends_at).getTime()<=clock);
 return <main className="mx-auto max-w-md p-4 pb-24">{loading?<p role="status">Loading outing…</p>:!outing?<><h1 className="text-xl font-semibold">Outing unavailable</h1><p className="mt-2">It may not have been shared with your account.</p></>:<><p className="text-sm text-gray-600">Quick outing · {outing.is_owner?'Your plan':outing.host+'’s plan'}</p><h1 className="mt-2 text-2xl font-semibold">{outing.place}</h1><div className="mt-5 rounded-2xl border bg-white p-4"><p>{outingTime(outing.starts_at)}</p><p className="mt-1 text-sm text-gray-600">Until {outingTime(outing.ends_at)}</p>{outing.message && <p className="mt-4 whitespace-pre-wrap">{outing.message}</p>}</div><p className="mt-4 text-sm text-gray-600">Shared privately with the selected audience. People who join can be seen by other recipients.</p>
 {ended?<p role="status" className="mt-4 rounded-xl bg-gray-100 p-3">{outing.cancelled_at?'This outing was cancelled.':'This outing has ended.'}</p>:outing.is_owner?<button disabled={busy} onClick={()=>{if(window.confirm('Cancel this outing and notify the recipients?'))act('cancel_outing',{});}} className="mt-4 rounded-xl border p-3">{busy?'Please wait…':'Cancel outing'}</button>:<button disabled={busy} onClick={()=>act('respond_outing',{going:!outing.going})} className="mt-4 w-full rounded-xl bg-yellow-300 p-3 font-semibold">{busy?'Saving…':outing.going?'Change to not coming':'We’re coming'}</button>}
 <section className="mt-6"><h2 className="font-semibold">Who’s coming</h2>{outing.attendees.length?<ul className="mt-2 space-y-2">{outing.attendees.map((name,i)=><li key={i}>{name}</li>)}</ul>:<p className="mt-2 text-sm text-gray-600">No responses yet.</p>}</section></>}{error && <p role="alert" className="mt-4 text-red-700">{error}</p>}<Link href="/" className="mt-6 inline-block underline">Back to Home</Link></main>;
}
