 'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {enableDevicePush,deviceSetup} from '../../lib/push-client';
import {pushState} from '../../lib/push-preferences';
const titles=['Welcome to the beta','Add LinkLemon to your Home Screen','Choose your device alerts','Check your first notification','You’re ready to head out'];
export default function BetaWelcome({userId,standalone=false,progress,onAction,saving=false,progressError=''}){
 const [info,setInfo]=useState(null),[step,setStep]=useState(0),[open,setOpen]=useState(false),[done,setDone]=useState(false),[platform,setPlatform]=useState('computer'),[installed,setInstalled]=useState(false),[device,setDevice]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{if(!standalone && !userId)return;const c=new AbortController();fetch('/api/push/settings',{cache:'no-store',signal:c.signal}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error('Setup could not load.');if(!data.betaWelcome){if(standalone)setError('This walkthrough is available during the LinkLemon beta.');return;}setInfo(data);setOpen(standalone || !progress?.skippedAt);}).catch(e=>{if(e.name!=='AbortError' && standalone)setError(e.message);});setPlatform(/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel' && navigator.maxTouchPoints>1)?'apple':/Android/.test(navigator.userAgent)?'android':'computer');setInstalled(window.matchMedia('(display-mode: standalone)').matches || navigator.standalone===true);deviceSetup('status').then(d=>setDevice(d.registered)).catch(()=>{});return()=>c.abort();},[userId,standalone]);
 useEffect(()=>{setStep(progress?.step || 0);setDone(Boolean(progress?.completedAt));},[progress]);
 async function remember(next,finished=false){const action=finished?'welcome_complete':next>step?'welcome_next':'welcome_back';if(await onAction(action,{step})){setMessage('');setError('');if(finished && standalone)window.location.assign('/');}}
 async function enable(){setBusy(true);setError('');setMessage('Follow your browser’s permission prompt.');try{const settings=await enableDevicePush();setInfo(v=>({...v,settings}));setDevice(true);setMessage('This device is enabled. Any pause still applies.');}catch(e){setMessage('');setError(e.message);}finally{setBusy(false);}}
 async function test(){setBusy(true);setError('');try{await deviceSetup('test');setMessage('Test queued for this device. Switch away from LinkLemon and check your notifications. If nothing appears, check your phone’s notification settings.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 if(!info)return standalone?<p role="status" className="p-4">{error || 'Loading your beta setup…'}</p>:null;
 if(done && !standalone)return null;
 if(!open)return <section className="mb-5 rounded-2xl border bg-white p-4"><h2 className="font-semibold">Finish your beta setup</h2><p className="mt-1 text-sm text-gray-600">Add LinkLemon to your Home Screen and choose your alerts.</p><button onClick={()=>setOpen(true)} className="mt-3 rounded-xl bg-yellow-300 px-4 py-2 font-semibold">Finish setup</button></section>;
 return <section aria-labelledby="beta-welcome-title" className="mb-5 rounded-2xl border bg-white p-5 max-w-xl"><p className="text-xs font-semibold uppercase text-gray-500">Beta welcome · Step {step+1} of 5</p><h2 id="beta-welcome-title" className="mt-2 text-xl font-semibold">{titles[step]}</h2>
 {step===0 && <p className="mt-3 text-sm">Heading to the playground or getting out for a while? Use Heading out to tell your groups and connections so they can join you. During the beta, try it with people you know and use Report a problem to share feedback.</p>}
 {step===1 && <div className="mt-3 text-sm">{installed?<p>You’re already using the Home Screen app.</p>:platform==='apple'?<ol className="list-decimal pl-5 space-y-2"><li>Open getlinklemon.com in Safari.</li><li>Tap Share, then Add to Home Screen. Choose Open as Web App if offered, then Add.</li><li>Open LinkLemon from its new icon and sign in if asked.</li></ol>:platform==='android'?<ol className="list-decimal pl-5 space-y-2"><li>Open getlinklemon.com in Chrome.</li><li>Open the browser menu and choose Install app or Add to Home screen.</li><li>Open LinkLemon from its new icon.</li></ol>:<p>You can use LinkLemon in this browser. For phone testing, open getlinklemon.com on your phone and follow these steps there.</p>}<p className="mt-3 text-gray-600">On iPhone and iPad, use the Home Screen app to receive alerts. If setup restarts in the installed app, you can skip straight to device alerts.</p></div>}
 {step===2 && <div className="mt-3 text-sm"><p>Get an alert when someone heads out or invites you. You can turn alerts off or pause them for today, a day, a week, or until a time you choose. Your inbox keeps updates either way.</p><button disabled={busy || saving || !info.deliveryReady} onClick={enable} className="mt-3 rounded-xl bg-yellow-300 px-4 py-3 font-semibold disabled:opacity-50">{busy?'Please wait…':device?'Enable or confirm this device':'Enable alerts on this device'}</button>{!info.deliveryReady && <p className="mt-2">Device alerts are temporarily unavailable. You can finish setup later.</p>}</div>}
 {step===3 && <div className="mt-3 text-sm"><p>This sends only to this device. After tapping, switch away from LinkLemon to check the alert.</p><button disabled={busy || saving || !device || !info.deliveryReady || pushState(info.settings)!=='on'} onClick={test} className="mt-3 rounded-xl bg-yellow-300 px-4 py-3 font-semibold disabled:opacity-50">{busy?'Please wait…':'Send test notification'}</button>{(!device || pushState(info.settings)!=='on') && <p className="mt-2 text-gray-600">Enable this device and clear any pause before testing. You can also skip this step.</p>}<Link href="/notification-settings" className="mt-2 inline-block underline">Manage alerts and pauses</Link></div>}
 {step===4 && <div className="mt-3 text-sm"><p>Start with a group or connection, then use Heading out when you have something planned. You can return to this walkthrough from Notification settings.</p><div className="mt-3 flex gap-4"><Link href="/groups" className="underline">My groups</Link><Link href="/connections" className="underline">Connections</Link></div></div>}
 {(error || progressError) && <p role="alert" className="mt-3 text-sm text-red-700">{error || progressError}</p>}{message && <p role="status" className="mt-3 text-sm">{message}</p>}
 <div className="mt-5 flex flex-wrap gap-3 items-center">{step>0 && <button disabled={busy || saving} onClick={()=>remember(step-1)} className="rounded-xl border px-4 py-2">Back</button>}{step<4?<button disabled={busy || saving} onClick={()=>remember(step+1)} className="rounded-xl border px-4 py-2 font-semibold">{step===2 && !device?'Continue without alerts':step===3?'Continue':'Next'}</button>:<button disabled={busy || saving} onClick={()=>remember(4,true)} className="rounded-xl bg-yellow-300 px-4 py-2 font-semibold">{saving?'Saving...':'Get started'}</button>}<button disabled={busy || saving} onClick={async()=>{if(await onAction('welcome_skip'))setOpen(false);}} className="text-sm underline">Skip for now</button></div><p className="mt-3 text-xs text-gray-500">Progress is saved to your account across devices. The beta team can see setup and mission progress.</p></section>;
}
