'use client';
import {useEffect,useState} from 'react';
import {pauseUntil} from '../../lib/push-preferences';
export default function EmailSettings(){
 const [data,setData]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[choice,setChoice]=useState('today'),[custom,setCustom]=useState('');
 useEffect(()=>{const c=new AbortController();const t=setTimeout(()=>c.abort(),15000);fetch('/api/email/settings',{cache:'no-store',signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);}).catch(()=>setError('Email settings are not available yet.')).finally(()=>clearTimeout(t));return()=>{c.abort();clearTimeout(t);};},[]);
 async function save(action,enabled){setBusy(true);setError('');setMessage('');try{const until=action==='pause'?pauseUntil(choice,custom):undefined;const r=await fetch('/api/email/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,enabled,until}),signal:AbortSignal.timeout(15000)});const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);setMessage(action==='test'?'Test email queued for your signed-in email address. It may take a minute to arrive.':'Email preferences saved.');}catch(e){setError(e.message || 'Could not save email settings.');}finally{setBusy(false);}}
 const settings=data?.settings;const paused=settings?.paused_until && new Date(settings.paused_until)>new Date();
 return <section className="mt-5 rounded-2xl border bg-white p-4"><h2 className="font-semibold">Email notifications</h2><p className="mt-2 text-sm text-gray-600">Invitations, connection requests, event updates, and Heading out activity. Email is separate from device alerts; all updates still appear in your inbox.</p>{data && <><p className="mt-3 text-sm break-all">Send to {data.email}</p><p className="mt-2 text-sm">{!settings.enabled?'Off':paused?'Paused until '+new Date(settings.paused_until).toLocaleString():'On'}</p>{!data.deliveryReady && <p className="mt-2 text-sm text-gray-600">Delivery is being set up. You can save your preferences now.</p>}<button disabled={busy} onClick={()=>save(settings.enabled?'off':'enable')} className="mt-3 rounded-xl bg-yellow-300 px-4 py-3 font-semibold disabled:opacity-50">{settings.enabled?'Turn email off':'Enable email notifications'}</button><label className="mt-4 flex items-start gap-3 text-sm"><input type="checkbox" checked={settings.heading_out} disabled={busy} onChange={e=>save('heading_out',e.target.checked)} className="mt-1"/><span>Include Heading out alerts and responses</span></label>{settings.enabled && <><label className="mt-4 block text-sm">Pause email<select value={choice} onChange={e=>setChoice(e.target.value)} className="mt-2 w-full rounded-xl border p-3"><option value="today">Rest of today</option><option value="day">For 24 hours</option><option value="week">For one week</option><option value="until">Until a date and time</option></select></label>{choice==='until' && <label className="mt-3 block text-sm">Resume after<input type="datetime-local" value={custom} onChange={e=>setCustom(e.target.value)} className="mt-2 w-full rounded-xl border p-3"/></label>}<div className="mt-3 flex flex-wrap gap-3"><button disabled={busy} onClick={()=>save('pause')} className="rounded-xl border px-4 py-2">Pause email</button>{paused && <button disabled={busy} onClick={()=>save('resume')} className="underline">Clear email pause</button>}</div></>}<button disabled={busy || !data.deliveryReady || !settings.enabled || !!paused} onClick={()=>save('test')} className="mt-4 rounded-xl border px-4 py-2 text-sm disabled:opacity-50">Send test email</button><p className="mt-3 text-xs text-gray-600">Old alerts aren’t replayed after a pause. Every email includes an unsubscribe link. Use LinkLemon to respond to invitations and outings.</p></>}{error && <p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}{message && <p role="status" className="mt-3 text-sm">{message}</p>}</section>;
}
