'use client';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import {social} from '../../lib/social-client';
export default function HeadingOutPage() {
 const router=useRouter();const [audience,setAudience]=useState(null),[groups,setGroups]=useState([]),[people,setPeople]=useState([]),[place,setPlace]=useState(''),[message,setMessage]=useState(''),[when,setWhen]=useState('now'),[start,setStart]=useState(''),[duration,setDuration]=useState('120'),[review,setReview]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{const c=new AbortController();social('audience',undefined,c.signal).then(setAudience).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>c.abort();},[]);
 function toggle(id,values,setter){setter(values.includes(id)?values.filter(x=>x!==id):[...values,id]);setReview(false);}
 const selected=[...(audience?.groups || []).filter(i=>groups.includes(i.id)),...(audience?.people || []).filter(i=>people.includes(i.id))];
 async function submit(e){e.preventDefault();setError('');const starts=when==='now'?new Date():new Date(start);if(!Number.isFinite(starts.getTime()) || starts.getTime()<Date.now()-300000 || starts.getTime()>Date.now()+7*86400000){setError('Choose a time within the next seven days.');return;}if(!selected.length){setError('Choose at least one group or connection.');return;}if(!review){setReview(true);return;}setBusy(true);try{const result=await social('create_outing',{place:place.trim(),message:message.trim(),starts_at:starts.toISOString(),ends_at:new Date(starts.getTime()+Number(duration)*60000).toISOString(),groups,people});router.push('/outings/'+result.id);}catch(e){setError(e.message);setBusy(false);}}
 return <main className="mx-auto max-w-md p-4"><h1 className="text-2xl font-semibold">Heading out</h1><p className="mt-2 text-sm text-gray-600">Make a little room for company.</p><form onSubmit={submit} className="mt-5 space-y-5">
 <label className="block font-medium">Where are you going?<input required minLength={2} maxLength={120} value={place} onChange={e=>{setPlace(e.target.value);setReview(false);}} placeholder="e.g. Stewart Park playground" className="mt-2 w-full rounded-xl border p-3"/></label>
 <label className="block font-medium">When?<select value={when} onChange={e=>{setWhen(e.target.value);setReview(false);}} className="mt-2 w-full rounded-xl border p-3"><option value="now">Now</option><option value="later">Choose a time</option></select></label>
 {when==='later' && <label className="block font-medium">Start time<input type="datetime-local" required value={start} onChange={e=>{setStart(e.target.value);setReview(false);}} className="mt-2 w-full rounded-xl border p-3"/></label>}
 <label className="block font-medium">How long will you be there?<select value={duration} onChange={e=>{setDuration(e.target.value);setReview(false);}} className="mt-2 w-full rounded-xl border p-3">{[['30','30 minutes'],['60','1 hour'],['120','2 hours'],['180','3 hours'],['240','4 hours']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
 <label className="block font-medium">Message <span className="font-normal text-gray-500">(optional)</span><textarea maxLength={500} value={message} onChange={e=>{setMessage(e.target.value);setReview(false);}} className="mt-2 w-full rounded-xl border p-3" rows={3} placeholder="We’ll be near the swings!"/></label>
 <fieldset className="rounded-2xl border bg-white p-4"><legend className="px-1 font-semibold">Who should know?</legend>{!audience?<p role="status">Loading your circle…</p>:<>{[['groups','Your groups',groups,setGroups],['people','Connections',people,setPeople]].map(([key,title,values,setter])=><div key={key} className="mb-4"><h2 className="mb-2 font-medium">{title}</h2>{audience[key].length?audience[key].map(i=><label key={i.id} className="flex items-center gap-3 py-2"><input type="checkbox" checked={values.includes(i.id)} onChange={()=>toggle(i.id,values,setter)} className="h-5 w-5"/>{i.name}</label>):<p className="text-sm text-gray-600">{key==='people'?'No accepted connections yet.':'Join or create a group first.'}</p>}</div>)}<Link href="/connections" className="text-sm underline">Manage connections</Link></>}</fieldset>
 {review && <aside className="rounded-xl border border-yellow-300 bg-yellow-50 p-4"><h2 className="font-semibold">Ready to share?</h2><p className="mt-2">Notify {selected.map(i=>i.name).join(', ')}.</p><p className="mt-2 text-sm">Only you and selected recipients can see this outing. Recipients can see the names of people who join. Group members are selected when you send; anyone included more than once receives one notification.</p><p className="mt-2 text-sm">This first version sends in-app notifications. Device push is coming next.</p></aside>}
 {error && <p role="alert" className="text-red-700">{error}</p>}<button disabled={busy || !audience} className="w-full rounded-xl bg-yellow-300 p-3 font-semibold disabled:opacity-50">{busy?'Sharing…':review?'Share outing':'Review audience'}</button>
 </form></main>;
}
