'use client';
import {useEffect,useState} from 'react';
import EmailSettings from '../components/EmailSettings';
import Link from 'next/link';
import {enableDevicePush,deviceSetup} from '../../lib/push-client';
import {pauseUntil,pushState} from '../../lib/push-preferences';
export default function NotificationSettings(){
 const [device,setDevice]=useState(false),[platform,setPlatform]=useState('generic'),[installed,setInstalled]=useState(false);
 useEffect(()=>{setPlatform(/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel' && navigator.maxTouchPoints>1)?'apple':/Android/.test(navigator.userAgent)?'android':'generic');setInstalled(window.matchMedia('(display-mode: standalone)').matches || navigator.standalone===true);deviceSetup('status').then(d=>setDevice(d.registered)).catch(()=>{});},[]);
 const [settings,setSettings]=useState(null),[ready,setReady]=useState(false),[choice,setChoice]=useState('today'),[custom,setCustom]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[clock,setClock]=useState(Date.now());
 useEffect(()=>{const c=new AbortController();const loadingTimeout=setTimeout(()=>{c.abort();setError('Settings took too long to load. Please reload this page.');},15000);fetch('/api/push/settings',{cache:'no-store',signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setSettings(d.settings);setReady(d.deliveryReady);clearTimeout(loadingTimeout);}).catch(e=>{clearTimeout(loadingTimeout);if(e.name!=='AbortError')setError(e.message);});const timer=setInterval(()=>setClock(Date.now()),30000);return()=>{c.abort();clearTimeout(loadingTimeout);clearInterval(timer);};},[]);
 async function save(action){setBusy(true);setError('');setMessage('');try{const until=action==='pause'?pauseUntil(choice,custom):null;const response=await fetch('/api/push/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,until}),signal:AbortSignal.timeout(15000)});const d=await response.json();if(!response.ok)throw new Error(d.error);setSettings(d.settings);setClock(Date.now());setMessage(action==='off'?'Device alerts are off.':action==='resume'?'Pause cleared.': 'Pause saved.');}catch(e){setError(e.message || 'Please try again.');}finally{setBusy(false);}}
 async function enable(){setBusy(true);setError('');setMessage('Follow your browser’s permission prompt to enable alerts.');try{const saved=await enableDevicePush();setSettings(saved);setDevice(true);setMessage('This device is enabled. Any current pause still applies.');}catch(e){setMessage('');setError(e.message);}finally{setBusy(false);}}
 async function test(){setBusy(true);setError('');setMessage('');try{await deviceSetup('test');setMessage('Test queued for this device. Check for a LinkLemon notification. Sending does not guarantee your phone will display it.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 const state=pushState(settings,clock);const paused=settings?.paused_until && new Date(settings.paused_until).getTime()>clock;
 return <main className="mx-auto max-w-md p-4"><h1 className="text-2xl font-semibold">Notification settings</h1><p className="mt-2 text-sm text-gray-600">Stay in the loop when it suits you. Pauses apply to every device; invitations and updates still arrive in your inbox.</p>
 <section className="mt-5 rounded-2xl border bg-white p-4"><h2 className="font-semibold">Set up this device</h2><ol className="mt-3 space-y-4 text-sm"><li><strong>1. Add LinkLemon to your Home Screen</strong><p className="mt-1 text-gray-600">{installed?'You’re using the installed app.':platform==='apple'?'In Safari, open Share, choose Add to Home Screen, then open LinkLemon from its new icon.':platform==='android'?'Open your browser menu and choose Install app or Add to Home screen, then open LinkLemon from its icon.':'On your phone, add LinkLemon to your Home Screen. On a computer, you can also use a supported browser.'}</p></li><li><strong>2. Enable alerts below</strong><p className="mt-1 text-gray-600">{device?'This signed-in device is registered. Your availability settings still apply.':'You choose whether to allow alerts. We won’t ask until you tap Enable.'}</p></li><li><strong>3. Check a test notification</strong><p className="mt-1 text-gray-600">Sends only to this device. After tapping, switch away from LinkLemon to check the alert.</p><button onClick={test} disabled={busy || !device || !ready || state!=='on'} className="mt-2 rounded-xl border px-4 py-3 font-semibold disabled:opacity-50">Send test notification</button>{state==='paused' && <p className="mt-1 text-gray-600">Clear your pause before testing.</p>}</li></ol></section>
 <section className="mt-5 rounded-2xl border bg-white p-4"><h2 className="font-semibold">Device alerts</h2><p role="status" className="mt-2">{!settings?'Loading…':state==='on'?'On':state==='paused'?'Paused':'Off'}{paused?' · Paused until '+new Date(settings.paused_until).toLocaleString():''}</p>{!ready && <p className="mt-2 text-sm text-gray-600">Push delivery is being set up. You can choose your availability now; updates remain in your inbox.</p>}
 {<button disabled={busy || !settings || !ready} onClick={enable} className="mt-3 rounded-xl bg-yellow-300 px-4 py-3 font-semibold disabled:opacity-50">{busy?'Please wait…':'Enable alerts on this device'}</button>}<p className="mt-2 text-xs text-gray-600">Enable each device you want to receive alerts on. Turn alerts off or pause to quiet every device. Your browser will ask permission only when you enable alerts. On iPhone or iPad, add LinkLemon to your Home Screen first.</p>
 {settings?.enabled && <button disabled={busy} onClick={()=>save('off')} className="mt-3 rounded-xl border px-4 py-2">Turn alerts off</button>}
 </section><section className="mt-5 rounded-2xl border bg-white p-4"><h2 className="font-semibold">Unavailable for a while?</h2><label className="mt-3 block text-sm">Pause all device alerts<select value={choice} onChange={e=>setChoice(e.target.value)} className="mt-2 w-full rounded-xl border p-3"><option value="today">Rest of today</option><option value="day">For 24 hours</option><option value="week">For one week</option><option value="until">Until a date and time</option></select></label>{choice==='until' && <label className="mt-3 block text-sm">Resume after<input type="datetime-local" value={custom} onChange={e=>setCustom(e.target.value)} className="mt-2 w-full rounded-xl border p-3"/></label>}
 <button disabled={busy || !settings} onClick={()=>save('pause')} className="mt-3 rounded-xl bg-yellow-300 px-4 py-3 font-semibold disabled:opacity-50">{busy?'Saving…':'Pause alerts'}</button>{paused && <button disabled={busy} onClick={()=>save('resume')} className="ml-4 text-sm underline">Clear pause</button>}<p className="mt-3 text-xs text-gray-600">After the pause ends, alerts resume only if you have turned them on. Old alerts won’t be replayed.</p></section>
 <EmailSettings/>
 {error && <p role="alert" className="mt-4 text-red-700">{error}</p>}{message && <p role="status" className="mt-4 text-sm">{message}</p>}<div className="mt-5 flex flex-wrap gap-4"><Link className="underline" href="/notifications">Open inbox</Link><Link className="underline" href="/welcome">Beta welcome walkthrough</Link></div></main>;
}
